Add reactbase aa1
erebos-xyz/react-esite pull request #3
Opened 2020-06-24 20:20 UTC by petschna

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there are no standard files to start the project. #1

**What is the new behavior (if this is a feature change)?**
- Now there are standard files to kick the start of the project off. Closes #1

2020-06-25 18:27 UTC, Aichnerc approved these changes
LGTM, so what am I getting paid?

2020-07-01 18:43 UTC, petute approved these changes
Should be ok to merge.

2020-07-01 18:54 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-07-01 18:54 UTC, kleberbaum commented on src/components/pages/PageRoot.js
> +
```suggestion
```
Would be better.

2020-07-01 19:06 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-07-01 19:06 UTC, kleberbaum commented on src/Routes.js
>   * HomePage: A basic template page
```suggestion
 * PageRoot: A basic template page
```

2020-07-01 19:13 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-07-01 19:15 UTC, merged