Add erebosbase aa1
erebos-xyz/react-esite pull request #4
Opened 2020-06-24 20:23 UTC by petschna

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the website feels kind of bulky, because there is no dynamic in the website #2

**What is the new behavior (if this is a feature change)?**
- Now with the parallax effect the website feels more dynamic and smooth Closes #2

2020-06-25 18:29 UTC, Aichnerc approved these changes
LGTM, where's my check?

2020-07-01 18:47 UTC, petute approved these changes
Should be ok to merge.

2020-07-01 19:05 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-07-01 19:05 UTC, kleberbaum commented on src/Routes.js
>   * HomePage: A basic template page
```suggestion
 * RootPage: A basic template page
```

2020-07-01 19:05 UTC, kleberbaum commented on src/components/pages/PageRoot.js
> +
```suggestion
```

2020-07-01 19:05 UTC, kleberbaum commented on src/index.scss
>   */
```suggestion
```

2020-07-01 19:09 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-07-01 19:09 UTC, kleberbaum commented on src/Routes.js
> + * RootPage: A basic template page
```suggestion
 * PageRoot: A basic template page
```

2020-07-01 19:15 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-07-01 19:16 UTC, merged